import tomato from './styles/img/tomato.png'
import lettuce from './styles/img/lettuce.png'
import corn from './styles/img/corn.png'
import carrot from './styles/img/carrot.png'
import potato from './styles/img/potato.png'
import artichoke from './styles/img/artichoke.png'
import beetroot from './styles/img/beetroot.png'
import flower from './styles/img/flower.png'
import garlic from './styles/img/garlic.png'
import ginger from './styles/img/ginger.png'
import green_pepper from './styles/img/green_pepper.png'
import hot_pepper from './styles/img/hot_pepper.png'
import leek from './styles/img/leek.png'
import onion from './styles/img/onion.png'
import radish from './styles/img/radish.png'
import red_pepper from './styles/img/red_pepper.png'
import soybean from './styles/img/soybean.png'
import aubergine from './styles/img/aubergine.png'

export {tomato, lettuce, corn, carrot, potato, artichoke, beetroot, flower, garlic, ginger, green_pepper, hot_pepper, leek, onion, radish, red_pepper, soybean, aubergine}